name: Isolation Tests
on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 20
    runs-on:
      group: couchbase-runners
      labels: ubuntu-latest-m
    strategy:
      fail-fast: false
      matrix:
        couchbase-server-version: [ 'enterprise-7.6.1' ]
    services:
      couchbase:
        image: couchbase:${{ matrix.couchbase-server-version }}
        ports:
          - 8091:8091
          - 8092:8092
          - 8093:8093
          - 8094:8094
          - 8095:8095
          - 8096:8096
          - 8097:8097
          - 9102:9102
          - 9123:9123
          - 11210:11210
          - 11280:11280
    env:
      CB_CONNECTION_STRING: couchbase://localhost
      CB_USER: Administrator
      CB_PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 7
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm i

      - name: Build packages
        run: pnpm run build

      - name: Initialize Couchbase cluster
        run: pnpm dlx tsx tests/scripts/initTestCluster.ts

      - name: Vitest cache
        uses: actions/cache@v4
        with:
          path: ./node_modules/.vite/vitest/results.json
          key: vitest-cache-${{ github.ref_name }}
          restore-keys: |
            vitest-cache-main

      - name: Run all tests
        run: |
          for i in {1..50}; do
            NODE_OPTIONS="--max-old-space-size=8192" ./node_modules/.bin/vitest kv --project=project:keyspace-isolation --run
          done

      - name: Upload Segfault if any
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: segfault-${{ matrix.couchbase-server-version }}-${{ github.sha }}
          path: crash.log
          overwrite: true

      - name: Upload Tests Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-report-${{ matrix.couchbase-server-version }}-${{ github.sha }}
          path: tests-report
          overwrite: true
