name: Create GitHub Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: |
          export PREVIOUS_TAG=$(git tag --sort=-creatordate --merged origin/main | sed -n '2p')
          export LATEST_TAG=$(git tag --sort=-creatordate --merged origin/main | sed -n '1p')
          npx changelogithub --from $PREVIOUS_TAG --to $LATEST_TAG
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}