name: Tests
on:
  push:
    branches:
      - main
  issue_comment:
    types: [created]

jobs:
  test:
    if: >
      (github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip ci')) ||
      (github.event.issue.pull_request && startsWith(github.event.comment.body, '/test') && github.actor == 'JesusTheHun')
    timeout-minutes: 20
    runs-on:
      group: couchbase-runners
      labels: ubuntu-latest-m
    strategy:
      matrix:
        couchbase-server-version: [ 'enterprise-7.2.4', 'enterprise' ]
    services:
      couchbase:
        image: couchbase:${{ matrix.couchbase-server-version }}
        ports:
          - 8091:8091
          - 8092:8092
          - 8093:8093
          - 8094:8094
          - 8095:8095
          - 8096:8096
          - 8097:8097
          - 9102:9102
          - 9123:9123
          - 11210:11210
          - 11280:11280
    env:
      CB_CONNECTION_STRING: couchbase://localhost
      CB_USER: Administrator
      CB_PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci -ws --include-workspace-root

      - name: Build packages
        run: npm run build

      - name: Initialize Couchbase cluster
        run: npx tsx tests/scripts/initTestCluster.ts

      - name: Run all tests
        run: npm run test -- --bail 5

      - name: Upload Tests Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-report-${{ github.sha }}
          path: tests-report
          overwrite: true